site_name: Olas Stack Developer Documentation
site_url: https://stack.olas.network/
site_description: Developer documentation of Olas ecosystem products.
#repo_url: https://github.com/valory-xyz/docs
site_author: developer@valory.xyz
edit_uri: ""
copyright:  Copyright &copy; 2021 - 2023 Valory AG 


strict: true


theme:
  name: 'material'
  language: en
  favicon: images/favicon.ico
  logo: images/logo.svg  
  icon:
    admonition:
      abstract: material/book-open-variant  
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

extra_css:
  - stylesheets/extra.css


nav:
  - Home: 'index.md' 
  - Monetize an Agent on Marketplace:
    - Mech Tools: '!include ./mech-tools-dev/mkdocs.yml'
  - Hire an Agent on Marketplace:
    - Mech Client: '!include ./mech-client/mkdocs.yml'
  - Build with Olas Agent Frameworks:
    - Demo autonomous services: 
      - 'demos/index.md'
      - Hello World: '!include ./hello-world/mkdocs.yml'
      - Price oracle: 'demos/price-oracle/index.md'
    - Open Autonomy Framework: '!include ./open-autonomy/mkdocs.yml'
    - Open AEA Framework: '!include ./open-aea/mkdocs.yml'
  - Build with Other Agent Frameworks:
    - Olas SDK: 'olas-sdk/index.md'
  - Olas Protocol:
      - 'protocol/index.md'
      - Mint packages NFTs: 'protocol/mint_packages_nfts.md'
      - Manage the life cycle of a service: 'protocol/life_cycle_of_a_service.md'
      - Tokenomics: 'protocol/tokenomics.md'
      - Technical overview: 'protocol/technical_overview.md'
  # Currently disabled as does not fit in with current paths
  # - Toolkits:
  #     - 'products/index.md'
  #     - SMPKit: '!include ./autonomous-fund/mkdocs.yml'
  #     - MintKit: '!include ./agent-academy-1/mkdocs.yml'
  #     - CoordinationKit: '!include ./contribution-service/mkdocs.yml'
  #     - MLKit: '!include ./apy-oracle/mkdocs.yml'
  #     - OracleKit: '!include ./price-oracle/mkdocs.yml'
  #     - IEKit: '!include ./IEKit/mkdocs.yml'
  #     - GovKit: '!include ./governatooorr/mkdocs.yml'
  #     - MechKit: '!include ./mech/mkdocs.yml'
  #     - KeeperKit: '!include ./agent-academy-2/mkdocs.yml'
  #     - MessagingKit: '!include ./open-acn/mkdocs.yml'

plugins:
  - macros:
      on_error_fail: true
      on_undefined: strict
  - search
  - monorepo
  - redirects:
      redirect_maps:
        'protocol/register_packages_on-chain.md': 'protocol/mint_packages_nfts.md'
        'protocol/mint_packages_on-chain.md': 'protocol/mint_packages_nfts.md'
        'open-autonomy/guides/configure_access_external_chains.md': 'open-autonomy/configure_service/configure_access_external_chains.md'
        'open-autonomy/guides/service_configuration_file.md': 'open-autonomy/configure_service/service_configuration_file.md'
        'open-autonomy/deployment/on-chain_deployment_checklist.md': 'open-autonomy/configure_service/on-chain_deployment_checklist.md' 


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list  
  - md_in_html
  - toc:
      title: On this page
      toc_depth: 3


extra:
  open_aea: '[Open AEA](https://github.com/valory-xyz/open-aea)'
  open_aea_doc: '[Open AEA documentation](https://open-aea.docs.autonolas.tech)'
  open_aea_api: '[Open AEA API](https://open-aea.docs.autonolas.tech/api)'
  fsm_app: 'FSM App'
  open_autonomy: '[Open Autonomy](https://github.com/valory-xyz/open-autonomy)'
  open_autonomy_api: '[Open Autonomy API](https://stack.olas.network)'
  open_aea_repository: '[Open AEA repository](https://github.com/valory-xyz/open-aea)'
  open_autonomy_repository: '[Open Autonomy repository](https://github.com/valory-xyz/open-autonomy)'
  autonolas_whitepaper: '[Olas Whitepaper](https://www.autonolas.network/documents/whitepaper/Whitepaper%20v1.0.pdf)'
  autonolas_protocol: '[Olas Protocol](https://stack.olas.network/protocol)'
  autonolas_protocol_registry_dapp_link: 'https://registry.olas.network'
  autonolas_protocol_registry_dapp: '[Olas Protocol web app](https://registry.olas.network)'
  autonolas_protocol_tokenomics_dapp: '[Olas Tokenomics web app](https://tokenomics.olas.network)'
  olas_operate_quickstart: '[Quickstart](https://github.com/valory-xyz/quickstart)'
  olas_operate_app: '[Pearl App](https://olas.network/pearl)'
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/autonolas
      name: Olas on X
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/z2PT65jKqQ
      name: Olas on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/valory-xyz
      name: Olas on GitHub


extra_javascript:
    - https://unpkg.com/mermaid@8.10.1/dist/mermaid.min.js
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - javascripts/dynamic-hash.js
    