name: checks

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  checks:
    continue-on-error: False
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Sub-modules
        run: git submodule update --init --recursive
          
      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox]==0.2.2          
          pip install poetry
          poetry update
          poetry install --no-root
          sudo npm install -g markdown-spellcheck

      - name: Check submodules' versions
        run: tox -e check-submodules-versions

      - name: Check copyright
        run: tox -e check-copyright
        
      - name: Check spelling
        run: tox -e spell-check
        
      - name: Check doc links
        run: tox -e check-doc-links      

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9.0.0
        with:
          globs: /docs/*.md # optional, default is *.{md,markdown}